exclude_paths:
  - spec
  - tmp

detectors:
  ControlParameter:
    exclude:
      - PeoplesoftCourseClassData
  DataClump:
    exclude:
      - PeoplesoftCourseClassData
  DuplicateMethodCall:
    exclude:
      - PeoplesoftCourseClassData
  FeatureEnvy:
    exclude:
      - PeoplesoftCourseClassData
  IrresponsibleModule:
    exclude:
      - Days
      - PeoplesoftCourseClassData
      - RakeRunner
  ManualDispatch:
    exclude:
      - PeoplesoftCourseClassData
  NestedIterators:
    exclude:
      - PeoplesoftCourseClassData
  NilCheck:
    exclude:
      - PeoplesoftCourseClassData
  TooManyStatements:
    exclude:
      - PeoplesoftCourseClassData
  UncommunicativeVariableName:
    exclude:
      - PeoplesoftCourseClassData
  UnusedParameters:
    exclude:
      - Days
      - PeoplesoftCourseClassData
  UtilityFunction:
    exclude:
      - PeoplesoftCourseClassData
      - RakeRunner
