---
# file is used to populate config/credentials.yml -> config/credentials.rb
dev:
  endpoint: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_development', field='Hostname') %>
  username: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_development', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_development', field='password') %>
test:
  endpoint: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_test', field='Hostname') %>
  username: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_test', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_test', field='password') %>
qat:
  endpoint: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_staging', field='Hostname') %>
  username: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_staging', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_staging', field='password') %>
production:
  endpoint: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_production', field='Hostname') %>
  username: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_production', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/courses/integration_broker_production', field='password') %>
