#!/bin/bash
set -euo pipefail

SCRIPT_PATH="$0"
cd "$(dirname "$SCRIPT_PATH")/.."

LINT_ALL=${LINT_ALL:-"false"}

if [ "$LINT_ALL" = "true" ]; then
  git config --global safe.directory "${HOME}/.local/share/ruby-advisory-db"
  git config --global http.proxy http://kraken02.oit.umn.edu:3128
  git config --global https.proxy https://kraken02.oit.umn.edu:3128
  echo "==> Checking Gems..."

  if grep -E 'bin/bundle-audit\s+check.*--ignore' "$SCRIPT_PATH" > /dev/null; then
    echo "*****"
    echo "⚠️  Reminder: Please review the ignored CVEs or GitHub security advisories in $SCRIPT_PATH"
    echo "   Ensure that ignored advisories are still relevant and necessary."
    echo "*****"
  fi

  bin/bundle-audit check --update
fi

echo "==> Running Reek..."
bin/reek
echo "==> Running Standard..."
bin/standardrb --no-fix
