#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

# populate the secrets
echo "==> Populating the application secrets for '${ENVIRONMENT}'"
erb "config/credentials.yml.erb" > "config/credentials.yml"

# configure msmtp
erb "config/msmtprc.erb" > "${HOME}/.msmtprc"

echo "==> Started PeopleSoft Course Class Data"
echo "==> Using endpoint: '${INTEGRATION_BROKER_URL}'"
exec "$@"
