#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Running Lastpassify"
docker run \
  -it --rm \
  --pull always \
  -e LASTPASS_USERNAME=$(whoami) \
  -v "$(pwd):/workdir" \
  asrcustomsolutions/lastpass:latest \
  lastpassify config/credentials.example.yml config/credentials.yml -s -p

echo "==> Getting/Building Docker images"
docker compose build --no-cache

echo "==> All done!"
