#!/bin/sh

# script/bootstrap: Resolve all dev dependencies that PeoplesoftCourseClass requires to run.

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
brew update

command -v lpass >/dev/null 2>&1 || {
  echo "==> Installing LastPass-CLI…"
    brew install lastpass-cli
}
fi

if [ -f "Gemfile" ]; then
echo "==> Installing gem dependencies…"
bundle check >/dev/null 2>&1  || {
  bundle install
}
fi

set +e
lpass status | grep 'Not logged in' &> /dev/null
if [ $? == 0 ]; then
  echo "You forgot to login to lpass CLI. Try running 'lpass login $USER@umn.edu'"
  exit
else
  bundle exec lastpassify config/credentials.example.yml config/credentials.yml -s -p
fi
set -e

echo "==> All done!"
